const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(process.env.VIEWER_ROOT||path.join(__dirname,'../../docs'));
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith(path.sep))p+='index.html';fs.readFile(p,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',/\.(m?js)$/.test(p)?'application/javascript':p.endsWith('.html')?'text/html':'application/octet-stream');res.end(data);});}).listen(8768,'127.0.0.1');
const artifacts=path.resolve(__dirname,'../test-output');fs.mkdirSync(artifacts,{recursive:true});
(async()=>{let browser,page;try{
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('CONSOLE',m.text());}});
 await page.goto(process.env.VIEWER_URL||'http://127.0.0.1:8768/altbau/');await page.waitForFunction(()=>window.viewerState,null,{timeout:60000});
 if(process.env.SMOKE){await page.screenshot({path:path.join(artifacts,'bim-smoke.png')});console.log('READY',await page.evaluate(async()=>({box:viewerState.model.box,mode:viewerState.mode,coordinates:await viewerState.model.getCoordinates()})));return;}
 const settle=()=>page.evaluate(()=>viewerState.settled());
 if(process.env.INTERACTIVE){
  await page.locator('[data-tab=view]').click();await page.locator('#top').click();await page.waitForTimeout(500);
  const samples=await page.evaluate(async()=>{const s=viewerState,canvas=s.renderer.domElement,rect=canvas.getBoundingClientRect(),found=[];for(let x=rect.width*.32;x<rect.width*.7;x+=rect.width*.07){const mouse=s.world.renderer.getSize().set(rect.left+x,rect.top+rect.height*.48);const hit=await s.model.raycast({camera:s.camera,mouse,dom:canvas});if(hit)found.push({x:mouse.x,y:mouse.y,point:hit.point.toArray()});}return found;});
  assert(samples.length>=3,'Need test surfaces');console.log('HIT SAMPLES',samples);
  await page.locator('#app-tools [data-mode=length]').click();await page.locator('#measure-snap').uncheck();
  await page.mouse.move(samples[0].x,samples[0].y);await page.waitForTimeout(400);await page.mouse.click(samples[0].x,samples[0].y);
  await page.waitForFunction(()=>viewerState.measures.pointCount===1,null,{timeout:20000});
  await page.mouse.move(samples[2].x,samples[2].y);await page.waitForTimeout(1000);await page.mouse.click(samples[2].x,samples[2].y);
  await page.waitForFunction(()=>viewerState.measures.tools.length.list.size===1,null,{timeout:15000});
  const measured=await page.evaluate(()=>[...viewerState.measures.tools.length.list][0].distance());const expected=Math.hypot(...samples[0].point.map((n,i)=>n-samples[2].point[i]));assert(Math.abs(measured-expected)<.05,`${measured} vs ${expected}`);
  await page.screenshot({path:path.join(artifacts,'bim-measure-interactive.png')});
  await page.locator('#measure-clear').click();await page.mouse.click(samples[0].x,samples[0].y);await page.mouse.click(samples[2].x,samples[2].y);await page.waitForFunction(()=>viewerState.measures.tools.length.list.size===1,null,{timeout:20000});assert(Math.abs(await page.evaluate(()=>[...viewerState.measures.tools.length.list][0].distance())-expected)<.05,'Rapid clicks must keep distinct coordinates');
  const triangle=[samples[0],samples[2],{x:samples[2].x,y:samples[2].y+65}];
  const trianglePoints=await page.evaluate(async(points)=>{const s=viewerState,result=[];for(const p of points){const hit=await s.model.raycast({camera:s.camera,mouse:s.world.renderer.getSize().set(p.x,p.y),dom:s.renderer.domElement});result.push(hit?.point.toArray());}return result;},triangle);assert(trianglePoints.every(Boolean));
  await page.locator('#app-tools [data-mode=area]').click();
  for(let i=0;i<triangle.length;i++){const p=triangle[i];await page.mouse.click(p.x,p.y);await page.waitForFunction(n=>viewerState.measures.pointCount===n,i+1,{timeout:20000});}
  await page.locator('#measure-finish').click();await page.waitForFunction(()=>viewerState.measures.tools.area.list.size===1,null,{timeout:20000});
  const area=await page.evaluate(()=>[...viewerState.measures.tools.area.list][0].rawValue);console.log('AREA DATA',area,trianglePoints,await page.evaluate(()=>viewerState.measures.serialize().measurements));
  const a=trianglePoints[1].map((n,i)=>n-trianglePoints[0][i]),b=trianglePoints[2].map((n,i)=>n-trianglePoints[0][i]);const cross=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];assert(Math.abs(area-Math.hypot(...cross)/2)<.1);
  await page.locator('#app-tools [data-mode=angle]').click();
  for(const p of triangle){await page.mouse.move(p.x,p.y);await page.waitForTimeout(900);await page.mouse.click(p.x,p.y);await page.waitForTimeout(900);}
  await page.waitForFunction(()=>viewerState.measures.tools.angle.list.size===1,null,{timeout:20000});assert(Math.abs(await page.evaluate(()=>[...viewerState.measures.tools.angle.list][0].value)-90)<.2);
  console.log('PASS interactive area/angle',area);
  await page.keyboard.press('Escape');await page.locator('[data-tab=view]').click();await page.locator('[data-cut-axis="[0,-1,0]"]').click();
  await page.locator('#section-slider').fill('0');await page.locator('#section-slider').dispatchEvent('input');await page.waitForTimeout(300);
  await page.screenshot({path:path.join(artifacts,'bim-section.png')});assert.equal(await page.evaluate(()=>viewerState.world.renderer.clippingPlanes.length),1);
  const clippedHit=await page.evaluate(async p=>{const s=viewerState;await s.fragments.update(true);const hit=await s.model.raycast({camera:s.camera,mouse:s.world.renderer.getSize().set(p.x,p.y),dom:s.renderer.domElement});return hit?.point.y;},samples[0]);assert(clippedHit===undefined||clippedHit<.01,'Clipped roof must not remain pickable');
  console.log('PASS actual interactive measurement',measured,'expected',expected);assert.deepEqual(errors,[]);return;
 }
 await page.locator('#eg').click();await settle();
 const actual=await page.evaluate(async()=>{const a=[];for(const[k,g]of viewerState.groups)a.push([k,(await viewerState.model.getVisible(g.ids)).every(v=>v===(k==='EG'))]);return a;});assert(actual.every(x=>x[1]));
 await page.locator('#all').click();await settle();
 await page.locator('#search').fill('EG Mauerwerk');await page.locator('#results button').first().click();
 await page.waitForFunction(()=>viewerState.properties);assert.match(await page.locator('#properties').innerText(),/Grundlage/);assert.match(await page.locator('#properties').innerText(),/Rekonstruktion/);
 await page.screenshot({path:path.join(artifacts,'bim-properties.png')});
 await page.locator('#isolate-selected').click();await settle();assert.equal(await page.evaluate(()=>viewerState.serializeView().visible.length),1);
 await page.locator('#hide-selected').click();await settle();assert.equal(await page.evaluate(()=>viewerState.serializeView().visible.length),0);
 await page.locator('[data-tab=model]').click();await page.locator('#all').click();await settle();assert.equal(await page.evaluate(()=>viewerState.serializeView().visible.length),2249);
 await page.locator('[data-tab=view]').click();await page.locator('[data-cut-axis="[0,-1,0]"]').click();assert.equal(await page.evaluate(()=>viewerState.clipper.list.size),1);
 await page.locator('#section-slider').fill('-3');await page.locator('#section-slider').dispatchEvent('input');
 const saved=await page.evaluate(()=>viewerState.serializeView());assert.equal(saved.planes.length,1);
 await page.locator('#section-clear').click();await page.evaluate(data=>viewerState.importView(data),saved);assert.equal(await page.evaluate(()=>viewerState.clipper.list.size),1);
 await page.locator('#section-clear').click();
 await page.locator('#projection').selectOption('Orthographic');await page.waitForFunction(()=>viewerState.world.camera.projection.current==='Orthographic');
 await page.locator('#top').click();await page.waitForFunction(()=>viewerState.world.camera.mode.id==='Plan');
 await page.evaluate(()=>viewerState.world.camera.controls.zoomTo(2.5,false));const zoomView=await page.evaluate(()=>viewerState.serializeView());
 await page.evaluate(()=>viewerState.world.camera.controls.zoomTo(.6,false));await page.evaluate(data=>viewerState.importView(data),zoomView);
 assert(Math.abs(await page.evaluate(()=>viewerState.camera.zoom)-2.5)<.001);
 await page.locator('#top').click();await page.waitForFunction(()=>viewerState.world.camera.mode.id==='Plan');await page.locator('#projection').selectOption('Perspective');
 await page.waitForFunction(()=>viewerState.world.camera.projection.current==='Perspective'&&viewerState.world.camera.mode.id==='Orbit');
 assert(await page.evaluate(()=>viewerState.world.camera.controls.azimuthRotateSpeed>0&&viewerState.world.camera.controls.polarRotateSpeed>0));
 await page.locator('#walk-start').click();await page.waitForFunction(()=>viewerState.mode==='walk');const before=await page.evaluate(()=>viewerState.camera.position.toArray());
 await page.keyboard.down('KeyW');await page.waitForTimeout(400);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>viewerState.camera.position.toArray());assert(Math.hypot(...before.map((n,i)=>n-after[i]))>.15);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>viewerState.mode),'select');
 await page.locator('[data-tab=measure]').click();
 const measurements={format:'altbau-measurements',version:1,measurements:[{type:'length',points:[[0,12,0],[3,12,4]]},{type:'area',points:[[0,12,0],[2,12,0],[2,12,3],[0,12,3]]},{type:'angle',points:[[1,12,0],[0,12,0],[0,12,1]]}]};
 await page.locator('#measure-import').setInputFiles({name:'measures.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(measurements))});
 await page.waitForFunction(()=>viewerState.measures.tools.length.list.size===1);
 const values=await page.evaluate(()=>Object.fromEntries(Object.entries(viewerState.measures.tools).map(([k,t])=>[k,[...t.list][0].value])));assert.deepEqual(values,{length:500,area:6,angle:90});
 assert.deepEqual(await page.evaluate(()=>viewerState.measures.serialize().measurements),measurements.measurements);
 await page.locator('#measure-unit').selectOption('m');assert.match(await page.locator('#measure-list').innerText(),/5 m/);
 await page.locator('#measure-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"bad"}')});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('gültige'));assert.equal(await page.evaluate(()=>viewerState.measures.tools.length.list.size),1);
 const [measurementDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#measure-export').click()]);assert.equal(measurementDownload.suggestedFilename(),'Altbau-Messungen.json');assert.equal(await measurementDownload.failure(),null);
 const [screenshotDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#screenshot').click()]);assert.equal(screenshotDownload.suggestedFilename(),'Altbau-Ansicht.png');assert.equal(await screenshotDownload.failure(),null);
 await page.locator('[data-tab=model]').click();await page.locator('#reset').click();await page.waitForTimeout(300);await page.screenshot({path:path.join(artifacts,'bim-desktop.png')});
 await page.evaluate(()=>viewerState.measures.clear());await page.setViewportSize({width:390,height:844});await page.locator('#toggle').click();await page.waitForTimeout(400);await page.screenshot({path:path.join(artifacts,'bim-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(page.url());await mobile.waitForFunction(()=>window.viewerState,null,{timeout:60000});await mobile.locator('[data-tab=view]').tap();await mobile.locator('#walk-start').tap();await mobile.waitForFunction(()=>viewerState.mode==='walk');await mobile.locator('#toggle').tap();
 const mobileBefore=await mobile.evaluate(()=>viewerState.camera.position.toArray());const box=await mobile.locator('[data-move=forward]').boundingBox(),cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await mobile.waitForTimeout(300);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const mobileAfter=await mobile.evaluate(()=>viewerState.camera.position.toArray());assert(Math.hypot(...mobileBefore.map((n,i)=>n-mobileAfter[i]))>.1);await mobile.screenshot({path:path.join(artifacts,'bim-walk-mobile.png')});await mobile.close();
 const response=await page.request.get(new URL('model.ifc',page.url()).href);assert(response.ok());assert((await response.text()).startsWith('ISO-10303-21;'));
 assert.deepEqual(errors,[]);console.log('PASS properties, visibility, isolate/hide, cuts, view roundtrip, projection, walking, length/area/angle, measurement roundtrip, invalid import, mobile, IFC download',values);
}catch(e){if(page){console.log('STATUS',await page.locator('#status').textContent(),'NOTICE',await page.locator('#notice').textContent());await page.screenshot({path:path.join(artifacts,'bim-failure.png')});}throw e;}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
